name: Deploy

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            git clone https://github.com/${{ github.repository }} ${{ github.SERVER_APP_PATH }}
            cd ${{ github.SERVER_APP_PATH }}
            sudo docker compose down
            docker compose up -d
